### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mehcode** [mehcode/arc-rs#2]
##### Current Focus
 * Ergonomic API
 * Correctness
 * macOS

##### Tasks

 - [x] Split `Context` into 2 parts; `Context`, and `Application`. `Application` gets `!Send` but frees up `Context` to remove the lock and `unsafe impl Send { ... }`. Nodes will only store a weak ref to `Context` vs. all of `Application`.

 - [x] Use `slotmap` in `Context` to store nodes.

 - [x] `arc::View(arc::os::View, ..)` becomes `arc::View(slotmap::Key, ..)`. All (necessary) methods are wrapped in `maybe_execute_in_main_thread` blocks. 

 - [x] Consider making `Context` a singleton. It's incorrect to make more than one of them in macOS. Same as in Windows. And a singleton would remove the need to ferry it around. `Context::get()` if needing to get a ref to the singleton.

##### Unresolved questions

 - [ ]  Decide how event propagation should work. Currently it doesn't at all. I'll likely make native propagation work first and stop at the first Arc event handler. But there should probably be a way to propagate further.
